#!/usr/bin/env bash
#transfers a file from our client to a server

if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

transfer_file="$1"
PATH="$2"
username="$3"
SSH_KEY="$4"

scp -o  StrictHostKeyChecking=no -i "$SSH_KEY" "$transfer_file" "$username"@"$PATH":~
