#!/usr/bin/env bash
# Install nginx web server

sudo apt update
sudo apt install -y nginx

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx reload
