#!/usr/bin/env bash
# Install nginx web server

sudo apt update
sudo apt install -y nginx

sudo service nginx start

sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx reload
