#!/usr/bin/env bash
# Configure Nginx server to redirecting to another page
apt-get update
apt-get install -y nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

link="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "9i $link" /etc/nginx/sites-available/default

sudo service nginx reload
