#!/usr/bin/env bash
# custom 404 page that contains the string Ceci n'est pas une page

sudo apt update
sudo apt install -y nginx

sudo ufw allow 'Nginx HTTP'
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

link="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;"
sudo sed -i "9i $link" /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default


sudo service nginx reload
