#!/usr/bin/env bash
#configure web-02 to be identical to web-01
sudo apt update
sudo apt install -y nginx

sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    add_header X-Served-By $HOSTNAME;

    root   /var/www/html;
    index  index.html index.htm index.nginx-debian.html;

    server_name _;
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }

    rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx reload
