#!/usr/bin/env bash
# make your fix short and sweet.
sed -i 's/listen [0-9]\+/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:[0-9]\+/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
pkill -1 nginx
