#!/usr/bin/env bash
# This script is displaying "Best School" 9 times

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 8 ]
    then
        echo "good luck"
    elif [ $i -eq 4 ]
    then
        echo "bad luck"
    else
        echo "Best School"
    fi
    ((i++))
done
